[tool.poetry]
name = "Apos-Backend"
version = "0.0.1"
description = "The Agile Pizza Order Service"
authors = ["Arne Beer <contact@arne.beer>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.7"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
